name: Push to ZHdK Gitlab

on:
  - push
  - delete

jobs:
  sync:
    runs-on: ubuntu-latest
    name: ZHdK Gitlab Mirror Action
    steps:
      - name: Checkout on Github
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to Gitlab
        uses: saderi/push-to-gitlab@v1
        with:
          gitlab_repository: 'https://gitlab.zhdk.ch/dbisig/dummy_repo_mirror'
          gitlab_token: ${{ secrets.TARGET_TOKEN }}
